name: Build and test

on: 
 pull_request:
 workflow_dispatch:

jobs:
  build-test-macos12:
    runs-on: macos-12
    strategy:
     matrix:
      xcode-version: [13.4.1, 14.0.1]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      
      - name: Install dependencies in Gemfile
        run: gem install fastlane
      
      - name:  Unit Tests, using Xcode ${{ matrix.xcode-version }}
        run: fastlane scan --devices "iPhone 8,iPhone 11"
        env:
         DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
         
  build-test-macos13:
    runs-on: macos-13
    strategy:
     matrix:
      xcode-version: [14.2, 14.3]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      
      - name: Install dependencies in Gemfile
        run: gem install fastlane
      
      - name:  Unit Tests, using Xcode ${{ matrix.xcode-version }}
        run: fastlane scan --devices "iPhone 8,iPhone 13"
        env:
         DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
  
  build-spm:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
        
      - name: Build spm
        working-directory: WWLayoutExample/WWLayoutTV
        run: | 
          xcodebuild build \
           -project "WWLayoutTV.xcodeproj" \
           -scheme "WWLayoutTV" \
           -destination "platform=tvOS Simulator,name=Apple TV"
